#!/bin/sh
set -e

if id "science" >/dev/null 2>&1; then
  echo "user exists!"
else
  useradd -G sudo science
fi

echo -e "${DB_PASSWORD}\n${DB_PASSWORD}\n" | passwd science

/usr/sbin/sshd -D &
apache2-foreground
